### ISSUE TITLE
String to convert base36

### ISSUE THREAD

**Issue by jadhavmanoj** [tonyseek/python-base36#1]
in current base36 conversion not able to convert string. Can you please help me for converting string to base36.
Thanks,
Manoj

**Comment by tonyseek** [comment]
The `base36.dumps` could accept integer only. It is by design.

Maybe you need `base36.dumps(int('11111'))`?

**Comment by jadhavmanoj** [comment]
But String could be alphanumeric.

It wont work for base36.dumps(int('test211')).

 is there any other way to get this?

**Comment by tonyseek** [comment]
Hmm.. This library have support for conversion between 10-base numbers and 36-base numbers only. `'test211'` is not an expected input for it.
